<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>Exceptions hierarchy &mdash; fantastico 0.5.1-b131 documentation</title>
    
    <link rel="stylesheet" href="../_static/default.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    '../',
        VERSION:     '0.5.1-b131',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <link rel="top" title="fantastico 0.5.1-b131 documentation" href="../index.html" />
    <link rel="up" title="Fantastico features" href="features.html" />
    <link rel="next" title="Request lifecycle" href="request_response.html" />
    <link rel="prev" title="Fantastico features" href="features.html" /> 
  </head>
  <body>
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="request_response.html" title="Request lifecycle"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="features.html" title="Fantastico features"
             accesskey="P">previous</a> |</li>
        <li><a href="../index.html">fantastico 0.5.1-b131 documentation</a> &raquo;</li>
          <li><a href="features.html" accesskey="U">Fantastico features</a> &raquo;</li> 
      </ul>
    </div>  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body">
            
  <div class="section" id="exceptions-hierarchy">
<h1>Exceptions hierarchy<a class="headerlink" href="#exceptions-hierarchy" title="Permalink to this headline">¶</a></h1>
<dl class="class">
<dt id="fantastico.exceptions.FantasticoError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoError" title="Permalink to this definition">¶</a></dt>
<dd><img alt="../_images/exceptions.png" src="../_images/exceptions.png" />
<p><strong>FantasticoError</strong> is the base of all exceptions raised within fantastico framework. It describe common attributes that
each concrete fantastico exception must provide. By default all fantastico exceptions inherit FantasticoError exception.
We do this because each raised unhandled FantasticoError is map to a specific exception response. This strategy guarantees
that at no moment errors will cause fantastico framework wsgi container to crash.</p>
<dl class="attribute">
<dt id="fantastico.exceptions.FantasticoError.http_code">
<tt class="descname">http_code</tt><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoError.http_code"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoError.http_code" title="Permalink to this definition">¶</a></dt>
<dd><p>This method returns the http code on which this exception is mapped.</p>
</dd></dl>

</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoControllerInvalidError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoControllerInvalidError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoControllerInvalidError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoControllerInvalidError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is raised whenever a method is decorated with
<a class="reference internal" href="mvc.html#fantastico.mvc.controller_decorators.Controller" title="fantastico.mvc.controller_decorators.Controller"><tt class="xref py py-class docutils literal"><span class="pre">fantastico.mvc.controller_decorators.Controller</span></tt></a> and the number of arguments is not correct. Usually
developer forgot to add request as argument to the controller.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoClassNotFoundError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoClassNotFoundError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoClassNotFoundError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoClassNotFoundError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is raised whenever code tries to dynamically import and instantiate a class which can not be resolved.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoNotSupportedError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoNotSupportedError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoNotSupportedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoNotSupportedError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is raised whenever code tries to do an operation that is  not supported.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoSettingNotFoundError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoSettingNotFoundError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoSettingNotFoundError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoSettingNotFoundError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is raised whenever code tries to obtain a setting that is not available in the current fantastico
configuration.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoDuplicateRouteError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoDuplicateRouteError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoDuplicateRouteError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoDuplicateRouteError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually raised by routing engine when it detects duplicate routes.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoNoRoutesError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoNoRoutesError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoNoRoutesError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoNoRoutesError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually raised by routing engine when no loaders are configured or no routes are registered.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoRouteNotFoundError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoRouteNotFoundError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoRouteNotFoundError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoRouteNotFoundError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually raised by routing engine when a requested url is not registered.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoNoRequestError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoNoRequestError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoNoRequestError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoNoRequestError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually raised when some components try to use fantastico.request from WSGI environ before
<a class="reference internal" href="request_response.html#fantastico.middleware.request_middleware.RequestMiddleware" title="fantastico.middleware.request_middleware.RequestMiddleware"><tt class="xref py py-class docutils literal"><span class="pre">fantastico.middleware.request_middleware.RequestMiddleware</span></tt></a> was executed.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoContentTypeError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoContentTypeError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoContentTypeError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoContentTypeError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually thrown when a mismatch between request accept and response content type. In
Fantastico we think it&#8217;s mandatory to fulfill requests correctly and to take in consideration sent headers.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoHttpVerbNotSupported">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoHttpVerbNotSupported</tt><big>(</big><em>http_verb</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoHttpVerbNotSupported"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoHttpVerbNotSupported" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually thrown when a route is accessed with an http verb which does not support.</p>
<dl class="attribute">
<dt id="fantastico.exceptions.FantasticoHttpVerbNotSupported.http_verb">
<tt class="descname">http_verb</tt><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoHttpVerbNotSupported.http_verb"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoHttpVerbNotSupported.http_verb" title="Permalink to this definition">¶</a></dt>
<dd><p>This property returns the http verb that caused the problems.</p>
</dd></dl>

</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoTemplateNotFoundError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoTemplateNotFoundError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoTemplateNotFoundError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoTemplateNotFoundError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually thrown when a controller tries to load a template which it does not found.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoIncompatibleClassError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoIncompatibleClassError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoIncompatibleClassError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoIncompatibleClassError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually thrown when we want to decorate / inject / mixin a class into another class
that does not support it. For instance, we want to build a <a class="reference internal" href="mvc.html#fantastico.mvc.model_facade.ModelFacade" title="fantastico.mvc.model_facade.ModelFacade"><tt class="xref py py-class docutils literal"><span class="pre">fantastico.mvc.model_facade.ModelFacade</span></tt></a>
with a class that does not extend <strong>BASEMODEL.</strong></p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoDbError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoDbError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoDbError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoDbError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually thrown when a database exception occurs. For one good example where this is used see
<a class="reference internal" href="mvc.html#fantastico.mvc.model_facade.ModelFacade" title="fantastico.mvc.model_facade.ModelFacade"><tt class="xref py py-class docutils literal"><span class="pre">fantastico.mvc.model_facade.ModelFacade</span></tt></a>.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoDbNotFoundError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoDbNotFoundError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoDbNotFoundError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoDbNotFoundError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually thrown when an entity does not exist but we try to update it. For one good example where this is
used see <a class="reference internal" href="mvc.html#fantastico.mvc.model_facade.ModelFacade" title="fantastico.mvc.model_facade.ModelFacade"><tt class="xref py py-class docutils literal"><span class="pre">fantastico.mvc.model_facade.ModelFacade</span></tt></a>.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoInsufficientArgumentsError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoInsufficientArgumentsError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoInsufficientArgumentsError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoInsufficientArgumentsError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually thrown when a component extension received wrong number of arguments. See
<a class="reference internal" href="component_reusage.html#fantastico.rendering.component.Component" title="fantastico.rendering.component.Component"><tt class="xref py py-class docutils literal"><span class="pre">fantastico.rendering.component.Component</span></tt></a>.</p>
</dd></dl>

<dl class="class">
<dt id="fantastico.exceptions.FantasticoUrlInvokerError">
<em class="property">class </em><tt class="descclassname">fantastico.exceptions.</tt><tt class="descname">FantasticoUrlInvokerError</tt><big>(</big><em>msg=None</em>, <em>http_code=400</em><big>)</big><a class="reference internal" href="../_modules/fantastico/exceptions.html#FantasticoUrlInvokerError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#fantastico.exceptions.FantasticoUrlInvokerError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is usually thrown when an internal url invoker fails. For instance, if a component reusage rendering
fails then this exception is raised.</p>
</dd></dl>

</div>


          </div>
        </div>
      </div>
      <div class="sphinxsidebar">
        <div class="sphinxsidebarwrapper">
  <h4>Previous topic</h4>
  <p class="topless"><a href="features.html"
                        title="previous chapter">Fantastico features</a></p>
  <h4>Next topic</h4>
  <p class="topless"><a href="request_response.html"
                        title="next chapter">Request lifecycle</a></p>
  <h3>This Page</h3>
  <ul class="this-page-menu">
    <li><a href="../_sources/features/exceptions.txt"
           rel="nofollow">Show Source</a></li>
  </ul>
<div id="searchbox" style="display: none">
  <h3>Quick search</h3>
    <form class="search" action="../search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    <p class="searchtip" style="font-size: 90%">
    Enter search terms or a module, class or function name.
    </p>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="request_response.html" title="Request lifecycle"
             >next</a> |</li>
        <li class="right" >
          <a href="features.html" title="Fantastico features"
             >previous</a> |</li>
        <li><a href="../index.html">fantastico 0.5.1-b131 documentation</a> &raquo;</li>
          <li><a href="features.html" >Fantastico features</a> &raquo;</li> 
      </ul>
    </div>

    <div class="footer">
        &copy; Copyright 2013, Radu Viorel Cosnita.
      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.2b1.
    </div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42788125-1', 'rcosnita.github.io');
  ga('send', 'pageview');
</script>

  </body>
</html>